# netlify.toml
[build]
  # Install dependencies and build
  command = "npm install --legacy-peer-deps && npm run build"
  # Set the output folder for Vite production build
  publish = "dist"

[build.environment]
  # Use Node.js 18 with npm 9 for better compatibility
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  # Disable npm fund messages and warnings
  NPM_CONFIG_FUND = "false"
  NPM_CONFIG_AUDIT = "false"
  NPM_CONFIG_UPDATE_NOTIFIER = "false"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[dev]